name: Reportar um erro na aplicação
description: Ajude-nos a melhorar reportando um problema com a aplicação
labels:
  - bug
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Por favor preencha este formulário o melhor que conseguir. Toda a informação que puder acrescentar aumentará as hipóteses de conseguirmos corrigir o problema. No entanto, se não souber o que colocar nalguma parte, não se preocupe. Faremos os possíveis para identificar a causa do erro com a informação que nos puder disponibilizar.
  - type: textarea
    id: what-happened
    attributes:
      label: Descrição do problema
      description: |
        Descreva o problema o melhor que conseguir. Se possível, explique os passos necessários para reproduzir o problema.
        Considere adicionar capturas de ecrã que ajudem a explicar o problema.
      placeholder: Uma descrição clara e concisa do problema.
    validations:
      required: true
  - type: textarea
    id: what-should-happen
    attributes:
      label: Comportamento esperado
      description: Explique o que acha que devia ter acontecido.
      placeholder: Uma descrição do que esperava que tivesse acontecido.
    validations:
      required: true
  - type: dropdown
    id: device-type
    attributes:
      label: Sistema operativo
      description: Que sistema operativo utiliza?
      options:
        - Android
        - iPhone
        - Windows
        - macOS
        - Linux
        - Outro
  - type: input
    id: device-version
    attributes:
      label: Versão do sistema operativo
      description: Qual a versão do seu sistema operativo?
      placeholder: Android 11
  - type: dropdown
    id: browser-type
    attributes:
      label: Que navegador utiliza?
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Aplicação Android
        - Outro
  - type: input
    id: browser-version
    attributes:
      label: Versão do navegador
      description: Qual a versão do seu navegador?
      placeholder: "109.0"
