# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: GlutenFreeMap
email: glutenfreemap@aaubry.net
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  glutenfreemap

languages:
- id: pt
  name: Português
  info:
    description:
      Uma aplicação para encontrar estabelecimentos adequados a celíacos.
  install:
    title: Instalar Aplicação
    description:
      Adicione esta aplicação ao seu ecrã inicial para que esteja sempre acessível.
    accept: Instalar
    cancel: Não obrigado
  links:
    map: Mapa
    about: Acerca

- id: en
  name: English
  info:
    description:
      An application to find establishments suitable for celiacs.
  install:
    title: Install Application
    description:
      Add this app to your home screen so it's always accessible.
    accept: Install
    cancel: No thanks
  links:
    map: Map
    about: About

- id: fr
  name: Français
  info:
    description:
      Une application pour trouver des établissements adaptés aux coeliaques.
  install:
    title: Installer l'Application
    description:
      Ajoutez cette application à votre écran d'accueil pour qu'elle soit toujours accessible.
    accept: Installer
    cancel: Non merci
  links:
    map: Carte
    about: À propos


# Build settings
# theme: minima
plugins: []
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
