# Copyright 2023 Antoine Aubry, Catarina Tavares
# 
# This file is part of GlutenFreeMap.
# 
# GlutenFreeMap is free software: you can redistribute it and/or modify it under the terms of
# the GNU General Public License as published by the Free Software Foundation,
# either version 3 of the License, or (at your option) any later version.
# 
# GlutenFreeMap is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with GlutenFreeMap.
# If not, see <https://www.gnu.org/licenses/>.

title: GlutenFreeMap
email: glutenfreemap@aaubry.net
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://glutenfreemap.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  glutenfreemap

languages:
- id: pt
  name: Português
  info:
    description:
      Uma aplicação para encontrar estabelecimentos adequados a celíacos em Portugal.
  install:
    title: Instalar Aplicação
    description:
      Adicione esta aplicação ao seu ecrã inicial para que esteja sempre acessível.
    accept: Instalar
    cancel: Não obrigado
  links:
    map: Mapa
    about: Acerca
    contacts: Reportar problemas
    language: Língua

- id: en
  name: English
  info:
    description:
      An application to find establishments suitable for celiacs in Portugal.
  install:
    title: Install Application
    description:
      Add this app to your home screen so it's always accessible.
    accept: Install
    cancel: No thanks
  links:
    map: Map
    about: About
    contacts: Report issues
    language: Language

- id: fr
  name: Français
  info:
    description:
      Une application pour trouver des établissements adaptés aux coeliaques au Portugal.
  install:
    title: Installer l'Application
    description:
      Ajoutez cette application à votre écran d'accueil pour qu'elle soit toujours accessible.
    accept: Installer
    cancel: Non merci
  links:
    map: Carte
    about: À propos
    contacts: Signaler un problème
    language: Langue

- id: es
  name: Español
  info:
    description:
      Una aplicación para encontrar establecimientos aptos para celíacos en Portugal.
  install:
    title: Instalar aplicación
    description:
      Agregue esta aplicación a su pantalla de inicio para que siempre esté accesible.
    accept: Instalar
    cancel: No gracias
  links:
    map: Mapa
    about: Sobre
    contacts: Reportar problemas
    language: Idioma

defaults:
  - scope:
      path: "*/map.md"
      type: pages
    values:
      includeScripts: map-scripts.html
